version: "3.3"
services:
  staticdataserver:
    build:
      context: ./staticDataServer
      dockerfile: Dockerfile
    command: yarn run start
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - app-network

  lwss:
    build:
      context: ./lobbyWSS
      dockerfile: Dockerfile
    command: yarn run start
    ports:
      - "5001:5001"
      - "5002:5002"
      - "5500-6000"

  fwss:
    build:
      context: ./gameWSS
      dockerfile: Dockerfile
    command: yarn run start
    ports: 
      - "6001: 6001"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: yarn run start
    ports:
      - "3000:3000"
      
#  mongo:
#    image: mongo
#    volumes:
#      - ./data:/data/db
#    ports:
#      - "27017:27017"
#    networks:
#      - app-network

networks:
  app-network:
    driver: bridge
